bits 32

; generated by abc (Phase3)
extern _MessageBoxA@16
extern _ExitProcess@4

section .data
    str_0 db "This is message 10 time", 0
    str_1 db "Yoshihiro App", 0

section .text
    global _main

_main:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 1
    mov ebx, ebp
    add ebx, -4
    mov [ebx], eax
L1:
    mov ebx, ebp
    add ebx, -4
    mov eax, [ebx]
    push eax
    mov eax, 10
    pop ecx
    cmp ecx, eax
    jg L3
    push    0
    push    str_1
    push    str_0
    push    0
    call    _MessageBoxA@16

L2:
    mov ebx, ebp
    add ebx, -4
    mov eax, [ebx]
    push eax
    mov eax, 1
    pop ecx
    add eax, ecx
    mov ebx, ebp
    add ebx, -4
    mov [ebx], eax
    jmp L1
L3:
    push 0
    call _ExitProcess@4
