bits 32

; generated by abc (Phase1) — reference output for t1.abp
extern _ExitProcess@4

section .data
    dummy db 0

section .text
    global _main

_main:
    push    0
    call    _ExitProcess@4
