bits 32

; generated by abc (Phase2)
extern _ExitProcess@4

section .data
    dummy db 0

section .text
    global _main

_main:
    push ebp
    mov ebp, esp
    sub esp, 8
    mov eax, 1
    mov [ebp-4], eax
    mov eax, 2
    mov [ebp-8], eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, 3
    pop ecx
    imul eax, ecx
    pop ecx
    add eax, ecx
    push eax
    call _ExitProcess@4
