bits 32

; generated by abc (Phase2)
extern _ExitProcess@4

section .data
    dummy db 0

section .text
    global _main

_main:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 1
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    pop ecx
    cmp ecx, eax
    jne L1
    mov eax, 10
    push eax
    call _ExitProcess@4
    jmp L2
L1:
    mov eax, 20
    push eax
    call _ExitProcess@4
L2:
