bits 32

; generated by abc (Phase3)
extern _ExitProcess@4

section .data
    dummy db 0

section .text
    global _main

_Add:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov ebx, ebp
    add ebx, 8
    mov eax, [ebx]
    push eax
    mov ebx, ebp
    add ebx, 12
    mov eax, [ebx]
    pop ecx
    add eax, ecx
    mov ebx, ebp
    add ebx, -4
    mov [ebx], eax
    mov ebx, ebp
    add ebx, -4
    mov eax, [ebx]
    mov esp, ebp
    pop ebp
    ret 8

_main:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 4
    push eax
    mov eax, 3
    push eax
    call _Add
    mov ebx, ebp
    add ebx, -4
    mov [ebx], eax
    mov ebx, ebp
    add ebx, -4
    mov eax, [ebx]
    push eax
    call _ExitProcess@4
