bits 32

; generated by abc (Phase3)
extern _ExitProcess@4

section .data
    dummy db 0

section .text
    global _main

_main:
    push ebp
    mov ebp, esp
    sub esp, 8
    mov eax, 1
    mov ebx, ebp
    add ebx, -4
    mov [ebx], eax
    mov eax, 0
    mov ebx, ebp
    add ebx, -8
    mov [ebx], eax
L1:
    mov ebx, ebp
    add ebx, -4
    mov eax, [ebx]
    push eax
    mov eax, 4
    pop ecx
    cmp ecx, eax
    jg L2
    mov ebx, ebp
    add ebx, -8
    mov eax, [ebx]
    push eax
    mov ebx, ebp
    add ebx, -4
    mov eax, [ebx]
    pop ecx
    add eax, ecx
    mov ebx, ebp
    add ebx, -8
    mov [ebx], eax
    mov ebx, ebp
    add ebx, -4
    mov eax, [ebx]
    push eax
    mov eax, 1
    pop ecx
    add eax, ecx
    mov ebx, ebp
    add ebx, -4
    mov [ebx], eax
    jmp L1
L2:
    mov ebx, ebp
    add ebx, -8
    mov eax, [ebx]
    push eax
    call _ExitProcess@4
