bits 32

; generated by abc (Phase4)
extern _ExitProcess@4

section .data
    dummy db 0

section .text
    global _main

_main:
    push ebp
    mov ebp, esp
    sub esp, 12
    mov eax, 0
    mov ebx, ebp
    add ebx, -8
    mov [ebx], eax
L1:
    mov ebx, ebp
    add ebx, -8
    mov eax, [ebx]
    push eax
    mov eax, 4
    pop ecx
    cmp ecx, eax
    jge L2
    mov ebx, ebp
    add ebx, -8
    mov eax, [ebx]
    push eax
    mov eax, 1
    pop ecx
    add eax, ecx
    push eax
    mov ebx, ebp
    add ebx, -8
    mov eax, [ebx]
    push eax
    mov ebx, ebp
    add ebx, -4
    pop eax
    add ebx, eax
    pop eax
    mov [ebx], al
    mov ebx, ebp
    add ebx, -8
    mov eax, [ebx]
    push eax
    mov eax, 1
    pop ecx
    add eax, ecx
    mov ebx, ebp
    add ebx, -8
    mov [ebx], eax
    jmp L1
L2:
    mov eax, 0
    mov ebx, ebp
    add ebx, -12
    mov [ebx], eax
    mov eax, 0
    mov ebx, ebp
    add ebx, -8
    mov [ebx], eax
L3:
    mov ebx, ebp
    add ebx, -8
    mov eax, [ebx]
    push eax
    mov eax, 4
    pop ecx
    cmp ecx, eax
    jge L4
    mov ebx, ebp
    add ebx, -12
    mov eax, [ebx]
    push eax
    mov ebx, ebp
    add ebx, -8
    mov eax, [ebx]
    push eax
    mov ebx, ebp
    add ebx, -4
    pop eax
    add ebx, eax
    movzx eax, [ebx]
    pop ecx
    add eax, ecx
    mov ebx, ebp
    add ebx, -12
    mov [ebx], eax
    mov ebx, ebp
    add ebx, -8
    mov eax, [ebx]
    push eax
    mov eax, 1
    pop ecx
    add eax, ecx
    mov ebx, ebp
    add ebx, -8
    mov [ebx], eax
    jmp L3
L4:
    mov ebx, ebp
    add ebx, -12
    mov eax, [ebx]
    push eax
    call _ExitProcess@4
