bits 32

; generated by abc (Phase4)
extern _ExitProcess@4

section .data
    dummy db 0

section .text
    global _main

_main:
    push ebp
    mov ebp, esp
    sub esp, 12
    mov eax, 10
    push eax
    mov eax, 0
    push eax
    mov ebx, ebp
    add ebx, -4
    pop eax
    add ebx, eax
    pop eax
    mov [ebx], al
    mov eax, 20
    push eax
    mov eax, 1
    push eax
    mov ebx, ebp
    add ebx, -4
    pop eax
    add ebx, eax
    pop eax
    mov [ebx], al
    mov eax, 30
    push eax
    mov eax, 2
    push eax
    mov ebx, ebp
    add ebx, -4
    pop eax
    add ebx, eax
    pop eax
    mov [ebx], al
    mov eax, 40
    push eax
    mov eax, 3
    push eax
    mov ebx, ebp
    add ebx, -4
    pop eax
    add ebx, eax
    pop eax
    mov [ebx], al
    mov eax, 0
    push eax
    mov ebx, ebp
    add ebx, -4
    pop eax
    add ebx, eax
    mov eax, ebx
    mov ebx, ebp
    add ebx, -8
    mov [ebx], eax
    mov eax, 0
    push eax
    mov ebx, ebp
    add ebx, -8
    mov eax, [ebx]
    mov ebx, eax
    pop eax
    add ebx, eax
    movzx eax, [ebx]
    push eax
    mov eax, 1
    push eax
    mov ebx, ebp
    add ebx, -8
    mov eax, [ebx]
    mov ebx, eax
    pop eax
    add ebx, eax
    movzx eax, [ebx]
    pop ecx
    add eax, ecx
    push eax
    mov eax, 2
    push eax
    mov ebx, ebp
    add ebx, -8
    mov eax, [ebx]
    mov ebx, eax
    pop eax
    add ebx, eax
    movzx eax, [ebx]
    pop ecx
    add eax, ecx
    push eax
    mov eax, 3
    push eax
    mov ebx, ebp
    add ebx, -8
    mov eax, [ebx]
    mov ebx, eax
    pop eax
    add ebx, eax
    movzx eax, [ebx]
    pop ecx
    add eax, ecx
    mov ebx, ebp
    add ebx, -12
    mov [ebx], eax
    mov ebx, ebp
    add ebx, -12
    mov eax, [ebx]
    push eax
    call _ExitProcess@4
