bits 32

; generated by abc (Phase4)
extern _ExitProcess@4

section .data
    dummy db 0

section .text
    global _main

_main:
    push ebp
    mov ebp, esp
    sub esp, 8
    mov eax, 0
    mov ebx, ebp
    add ebx, -4
    mov [ebx], eax
    mov ebx, ebp
    add ebx, -4
    mov eax, ebx
    mov ebx, ebp
    add ebx, -8
    mov [ebx], eax
    mov eax, 7
    push eax
    mov eax, 0
    push eax
    mov ebx, ebp
    add ebx, -8
    mov eax, [ebx]
    mov ebx, eax
    pop eax
    add ebx, eax
    pop eax
    mov [ebx], al
    mov ebx, ebp
    add ebx, -4
    mov eax, [ebx]
    push eax
    call _ExitProcess@4
