#include "interpriter.idx"	

#console

' « ‚±‚±‚©‚çƒvƒƒOƒ‰ƒ€‚ªÀs‚³‚ê‚Ü‚·
Main()

Function Main() As Integer
	Dim stack As Stack
    Dim s As String
    While True
    	
        Input s
        If compIgnCase(s, "quit") Then
            Exit While
        End If
		if compIgnCase(s, "printstack") Then
            stack.PrintStack()
            continue
        End If
		SetBuffer(s)
		parserToken = GetNextToken()
		Statement()
    Wend
	Main = 0:return
End Function


