#include "interpriter.idx"	

#console

' « ‚±‚±‚©‚çƒvƒƒOƒ‰ƒ€‚ªŽÀs‚³‚ê‚Ü‚·
Main()

Function Main() As Integer
	Dim stack As Stack
    Dim s As String
    While True
    	
        Print "->"
        Input s
        If compIgnCase(s, "quit") Then
            Exit While
        End If
		if compIgnCase(s, "printstack") Then
            stack.PrintStack()
            continue
        End If
		SetBuffer(s)
		While Not IsEof()
			Print GetNextCh()
		Wend
/*		
        Dim c = s[0] As Char
		Dim value As Double
		Dim a As Double
		Dim b As Double
		Select Case c
			Case Asc("+")
				a = stack.Pop()
				b = stack.Pop()
				value = a + b
				Print value
				stack.Push(value)
			Case Asc("-")
				a = stack.Pop()
				b = stack.Pop()
				value = a - b
				Print value
				stack.Push(value)
			Case Asc("/")
				a = stack.Pop()
				b = stack.Pop()
				value = a / b
				Print value
				stack.Push(value)
			Case Asc("*")
				a = stack.Pop()
				b = stack.Pop()
				value = a * b
				Print value
				stack.Push(value)
			Case Else
				value = Val(s)
				stack.Push(value)
		End Select

    
        Print s*/
    Wend
	Main = 0:return
End Function


