bits 32

; generated by abc
extern _MessageBoxA@16
extern _ExitProcess@4

section .data
    str_0 db "This is message ", 0
    str_1 db "My Yoshihiro App", 0

section .text
    global _main

_main:
    push    0
    push    str_1
    push    str_0
    push    0
    call    _MessageBoxA@16

    push    0
    call    _ExitProcess@4
